// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sqlop.proto
// Protobuf C++ Version: 5.27.0-dev

#include "sqlop.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace sql {

inline constexpr player_single_info::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : uuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        names_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        guid_{::uint64_t{0u}},
        avatar_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR player_single_info::player_single_info(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct player_single_infoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR player_single_infoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~player_single_infoDefaultTypeInternal() {}
  union {
    player_single_info _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 player_single_infoDefaultTypeInternal _player_single_info_default_instance_;

inline constexpr player_info_kv_str::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR player_info_kv_str::player_info_kv_str(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct player_info_kv_strDefaultTypeInternal {
  PROTOBUF_CONSTEXPR player_info_kv_strDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~player_info_kv_strDefaultTypeInternal() {}
  union {
    player_info_kv_str _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 player_info_kv_strDefaultTypeInternal _player_info_kv_str_default_instance_;

inline constexpr player_info_kv_int::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR player_info_kv_int::player_info_kv_int(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct player_info_kv_intDefaultTypeInternal {
  PROTOBUF_CONSTEXPR player_info_kv_intDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~player_info_kv_intDefaultTypeInternal() {}
  union {
    player_info_kv_int _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 player_info_kv_intDefaultTypeInternal _player_info_kv_int_default_instance_;

inline constexpr player_info_array::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_{},
        _data_cached_byte_size_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR player_info_array::player_info_array(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct player_info_arrayDefaultTypeInternal {
  PROTOBUF_CONSTEXPR player_info_arrayDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~player_info_arrayDefaultTypeInternal() {}
  union {
    player_info_array _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 player_info_arrayDefaultTypeInternal _player_info_array_default_instance_;

inline constexpr player_info::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        single_{nullptr},
        array_{nullptr},
        kv_int_{nullptr},
        kv_str_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR player_info::player_info(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct player_infoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR player_infoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~player_infoDefaultTypeInternal() {}
  union {
    player_info _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 player_infoDefaultTypeInternal _player_info_default_instance_;
}  // namespace sql
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_sqlop_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_sqlop_2eproto = nullptr;
const ::uint32_t
    TableStruct_sqlop_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::sql::player_info_array, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::sql::player_info_array, _impl_.data_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::sql::player_info_kv_int, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::sql::player_info_kv_int, _impl_.data_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::sql::player_info_kv_str, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::sql::player_info_kv_str, _impl_.data_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::sql::player_single_info, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::sql::player_single_info, _impl_.guid_),
        PROTOBUF_FIELD_OFFSET(::sql::player_single_info, _impl_.uuid_),
        PROTOBUF_FIELD_OFFSET(::sql::player_single_info, _impl_.names_),
        PROTOBUF_FIELD_OFFSET(::sql::player_single_info, _impl_.avatar_),
        PROTOBUF_FIELD_OFFSET(::sql::player_info, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::sql::player_info, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::sql::player_info, _impl_.single_),
        PROTOBUF_FIELD_OFFSET(::sql::player_info, _impl_.array_),
        PROTOBUF_FIELD_OFFSET(::sql::player_info, _impl_.kv_int_),
        PROTOBUF_FIELD_OFFSET(::sql::player_info, _impl_.kv_str_),
        0,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::sql::player_info_array)},
        {9, -1, -1, sizeof(::sql::player_info_kv_int)},
        {18, -1, -1, sizeof(::sql::player_info_kv_str)},
        {27, -1, -1, sizeof(::sql::player_single_info)},
        {39, 51, -1, sizeof(::sql::player_info)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::sql::_player_info_array_default_instance_._instance,
    &::sql::_player_info_kv_int_default_instance_._instance,
    &::sql::_player_info_kv_str_default_instance_._instance,
    &::sql::_player_single_info_default_instance_._instance,
    &::sql::_player_info_default_instance_._instance,
};
const char descriptor_table_protodef_sqlop_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013sqlop.proto\022\003sql\"!\n\021player_info_array\022"
    "\014\n\004data\030\001 \003(\003\"\"\n\022player_info_kv_int\022\014\n\004d"
    "ata\030\001 \003(\t\"\"\n\022player_info_kv_str\022\014\n\004data\030"
    "\001 \003(\t\"O\n\022player_single_info\022\014\n\004guid\030\001 \001("
    "\004\022\014\n\004uuid\030\002 \001(\014\022\r\n\005names\030\003 \001(\t\022\016\n\006avatar"
    "\030\004 \001(\005\"\257\001\n\013player_info\022\'\n\006single\030\001 \001(\0132\027"
    ".sql.player_single_info\022%\n\005array\030\002 \001(\0132\026"
    ".sql.player_info_array\022\'\n\006kv_int\030\003 \001(\0132\027"
    ".sql.player_info_kv_int\022\'\n\006kv_str\030\004 \001(\0132"
    "\027.sql.player_info_kv_strb\006proto3"
};
static ::absl::once_flag descriptor_table_sqlop_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_sqlop_2eproto = {
    false,
    false,
    392,
    descriptor_table_protodef_sqlop_2eproto,
    "sqlop.proto",
    &descriptor_table_sqlop_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_sqlop_2eproto::offsets,
    file_level_enum_descriptors_sqlop_2eproto,
    file_level_service_descriptors_sqlop_2eproto,
};
namespace sql {
// ===================================================================

class player_info_array::_Internal {
 public:
};

player_info_array::player_info_array(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sql.player_info_array)
}
inline PROTOBUF_NDEBUG_INLINE player_info_array::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::sql::player_info_array& from_msg)
      : data_{visibility, arena, from.data_},
        _data_cached_byte_size_{0},
        _cached_size_{0} {}

player_info_array::player_info_array(
    ::google::protobuf::Arena* arena,
    const player_info_array& from)
    : ::google::protobuf::Message(arena) {
  player_info_array* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:sql.player_info_array)
}
inline PROTOBUF_NDEBUG_INLINE player_info_array::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : data_{visibility, arena},
        _data_cached_byte_size_{0},
        _cached_size_{0} {}

inline void player_info_array::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
player_info_array::~player_info_array() {
  // @@protoc_insertion_point(destructor:sql.player_info_array)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void player_info_array::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
player_info_array::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(player_info_array, _impl_._cached_size_),
              false,
          },
          &player_info_array::MergeImpl,
          &player_info_array::kDescriptorMethods,
          &descriptor_table_sqlop_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> player_info_array::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_player_info_array_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sql::player_info_array>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated int64 data = 1;
    {::_pbi::TcParser::FastV64P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(player_info_array, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated int64 data = 1;
    {PROTOBUF_FIELD_OFFSET(player_info_array, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void player_info_array::Clear() {
// @@protoc_insertion_point(message_clear_start:sql.player_info_array)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* player_info_array::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sql.player_info_array)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated int64 data = 1;
  {
    int byte_size = _impl_._data_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          1, _internal_data(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sql.player_info_array)
  return target;
}

::size_t player_info_array::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sql.player_info_array)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated int64 data = 1;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int64Size(
        this->_internal_data())
    ;
    _impl_._data_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void player_info_array::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<player_info_array*>(&to_msg);
  auto& from = static_cast<const player_info_array&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sql.player_info_array)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_data()->MergeFrom(from._internal_data());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void player_info_array::CopyFrom(const player_info_array& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sql.player_info_array)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool player_info_array::IsInitialized() const {
  return true;
}

void player_info_array::InternalSwap(player_info_array* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
}

::google::protobuf::Metadata player_info_array::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class player_info_kv_int::_Internal {
 public:
};

player_info_kv_int::player_info_kv_int(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sql.player_info_kv_int)
}
inline PROTOBUF_NDEBUG_INLINE player_info_kv_int::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::sql::player_info_kv_int& from_msg)
      : data_{visibility, arena, from.data_},
        _cached_size_{0} {}

player_info_kv_int::player_info_kv_int(
    ::google::protobuf::Arena* arena,
    const player_info_kv_int& from)
    : ::google::protobuf::Message(arena) {
  player_info_kv_int* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:sql.player_info_kv_int)
}
inline PROTOBUF_NDEBUG_INLINE player_info_kv_int::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : data_{visibility, arena},
        _cached_size_{0} {}

inline void player_info_kv_int::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
player_info_kv_int::~player_info_kv_int() {
  // @@protoc_insertion_point(destructor:sql.player_info_kv_int)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void player_info_kv_int::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
player_info_kv_int::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(player_info_kv_int, _impl_._cached_size_),
              false,
          },
          &player_info_kv_int::MergeImpl,
          &player_info_kv_int::kDescriptorMethods,
          &descriptor_table_sqlop_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 35, 2> player_info_kv_int::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_player_info_kv_int_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sql::player_info_kv_int>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string data = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(player_info_kv_int, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string data = 1;
    {PROTOBUF_FIELD_OFFSET(player_info_kv_int, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\26\4\0\0\0\0\0\0"
    "sql.player_info_kv_int"
    "data"
  }},
};

PROTOBUF_NOINLINE void player_info_kv_int::Clear() {
// @@protoc_insertion_point(message_clear_start:sql.player_info_kv_int)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* player_info_kv_int::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sql.player_info_kv_int)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated string data = 1;
  for (int i = 0, n = this->_internal_data_size(); i < n; ++i) {
    const auto& s = this->_internal_data().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sql.player_info_kv_int.data");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sql.player_info_kv_int)
  return target;
}

::size_t player_info_kv_int::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sql.player_info_kv_int)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated string data = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_data().size());
  for (int i = 0, n = _internal_data().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_data().Get(i));
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void player_info_kv_int::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<player_info_kv_int*>(&to_msg);
  auto& from = static_cast<const player_info_kv_int&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sql.player_info_kv_int)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_data()->MergeFrom(from._internal_data());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void player_info_kv_int::CopyFrom(const player_info_kv_int& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sql.player_info_kv_int)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool player_info_kv_int::IsInitialized() const {
  return true;
}

void player_info_kv_int::InternalSwap(player_info_kv_int* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
}

::google::protobuf::Metadata player_info_kv_int::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class player_info_kv_str::_Internal {
 public:
};

player_info_kv_str::player_info_kv_str(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sql.player_info_kv_str)
}
inline PROTOBUF_NDEBUG_INLINE player_info_kv_str::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::sql::player_info_kv_str& from_msg)
      : data_{visibility, arena, from.data_},
        _cached_size_{0} {}

player_info_kv_str::player_info_kv_str(
    ::google::protobuf::Arena* arena,
    const player_info_kv_str& from)
    : ::google::protobuf::Message(arena) {
  player_info_kv_str* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:sql.player_info_kv_str)
}
inline PROTOBUF_NDEBUG_INLINE player_info_kv_str::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : data_{visibility, arena},
        _cached_size_{0} {}

inline void player_info_kv_str::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
player_info_kv_str::~player_info_kv_str() {
  // @@protoc_insertion_point(destructor:sql.player_info_kv_str)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void player_info_kv_str::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
player_info_kv_str::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(player_info_kv_str, _impl_._cached_size_),
              false,
          },
          &player_info_kv_str::MergeImpl,
          &player_info_kv_str::kDescriptorMethods,
          &descriptor_table_sqlop_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 35, 2> player_info_kv_str::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_player_info_kv_str_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sql::player_info_kv_str>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string data = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(player_info_kv_str, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string data = 1;
    {PROTOBUF_FIELD_OFFSET(player_info_kv_str, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\26\4\0\0\0\0\0\0"
    "sql.player_info_kv_str"
    "data"
  }},
};

PROTOBUF_NOINLINE void player_info_kv_str::Clear() {
// @@protoc_insertion_point(message_clear_start:sql.player_info_kv_str)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* player_info_kv_str::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sql.player_info_kv_str)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated string data = 1;
  for (int i = 0, n = this->_internal_data_size(); i < n; ++i) {
    const auto& s = this->_internal_data().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sql.player_info_kv_str.data");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sql.player_info_kv_str)
  return target;
}

::size_t player_info_kv_str::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sql.player_info_kv_str)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated string data = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_data().size());
  for (int i = 0, n = _internal_data().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_data().Get(i));
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void player_info_kv_str::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<player_info_kv_str*>(&to_msg);
  auto& from = static_cast<const player_info_kv_str&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sql.player_info_kv_str)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_data()->MergeFrom(from._internal_data());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void player_info_kv_str::CopyFrom(const player_info_kv_str& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sql.player_info_kv_str)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool player_info_kv_str::IsInitialized() const {
  return true;
}

void player_info_kv_str::InternalSwap(player_info_kv_str* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
}

::google::protobuf::Metadata player_info_kv_str::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class player_single_info::_Internal {
 public:
};

player_single_info::player_single_info(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sql.player_single_info)
}
inline PROTOBUF_NDEBUG_INLINE player_single_info::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::sql::player_single_info& from_msg)
      : uuid_(arena, from.uuid_),
        names_(arena, from.names_),
        _cached_size_{0} {}

player_single_info::player_single_info(
    ::google::protobuf::Arena* arena,
    const player_single_info& from)
    : ::google::protobuf::Message(arena) {
  player_single_info* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, guid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, guid_),
           offsetof(Impl_, avatar_) -
               offsetof(Impl_, guid_) +
               sizeof(Impl_::avatar_));

  // @@protoc_insertion_point(copy_constructor:sql.player_single_info)
}
inline PROTOBUF_NDEBUG_INLINE player_single_info::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : uuid_(arena),
        names_(arena),
        _cached_size_{0} {}

inline void player_single_info::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, guid_),
           0,
           offsetof(Impl_, avatar_) -
               offsetof(Impl_, guid_) +
               sizeof(Impl_::avatar_));
}
player_single_info::~player_single_info() {
  // @@protoc_insertion_point(destructor:sql.player_single_info)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void player_single_info::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.uuid_.Destroy();
  _impl_.names_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
player_single_info::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(player_single_info, _impl_._cached_size_),
              false,
          },
          &player_single_info::MergeImpl,
          &player_single_info::kDescriptorMethods,
          &descriptor_table_sqlop_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 36, 2> player_single_info::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_player_single_info_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sql::player_single_info>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 avatar = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(player_single_info, _impl_.avatar_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(player_single_info, _impl_.avatar_)}},
    // uint64 guid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(player_single_info, _impl_.guid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(player_single_info, _impl_.guid_)}},
    // bytes uuid = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(player_single_info, _impl_.uuid_)}},
    // string names = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(player_single_info, _impl_.names_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 guid = 1;
    {PROTOBUF_FIELD_OFFSET(player_single_info, _impl_.guid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // bytes uuid = 2;
    {PROTOBUF_FIELD_OFFSET(player_single_info, _impl_.uuid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // string names = 3;
    {PROTOBUF_FIELD_OFFSET(player_single_info, _impl_.names_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 avatar = 4;
    {PROTOBUF_FIELD_OFFSET(player_single_info, _impl_.avatar_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\26\0\0\5\0\0\0\0"
    "sql.player_single_info"
    "names"
  }},
};

PROTOBUF_NOINLINE void player_single_info::Clear() {
// @@protoc_insertion_point(message_clear_start:sql.player_single_info)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uuid_.ClearToEmpty();
  _impl_.names_.ClearToEmpty();
  ::memset(&_impl_.guid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.avatar_) -
      reinterpret_cast<char*>(&_impl_.guid_)) + sizeof(_impl_.avatar_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* player_single_info::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sql.player_single_info)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 guid = 1;
  if (this->_internal_guid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_guid(), target);
  }

  // bytes uuid = 2;
  if (!this->_internal_uuid().empty()) {
    const std::string& _s = this->_internal_uuid();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // string names = 3;
  if (!this->_internal_names().empty()) {
    const std::string& _s = this->_internal_names();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sql.player_single_info.names");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // int32 avatar = 4;
  if (this->_internal_avatar() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_avatar(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sql.player_single_info)
  return target;
}

::size_t player_single_info::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sql.player_single_info)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // bytes uuid = 2;
  if (!this->_internal_uuid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_uuid());
  }

  // string names = 3;
  if (!this->_internal_names().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_names());
  }

  // uint64 guid = 1;
  if (this->_internal_guid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_guid());
  }

  // int32 avatar = 4;
  if (this->_internal_avatar() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_avatar());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void player_single_info::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<player_single_info*>(&to_msg);
  auto& from = static_cast<const player_single_info&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sql.player_single_info)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_uuid().empty()) {
    _this->_internal_set_uuid(from._internal_uuid());
  }
  if (!from._internal_names().empty()) {
    _this->_internal_set_names(from._internal_names());
  }
  if (from._internal_guid() != 0) {
    _this->_impl_.guid_ = from._impl_.guid_;
  }
  if (from._internal_avatar() != 0) {
    _this->_impl_.avatar_ = from._impl_.avatar_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void player_single_info::CopyFrom(const player_single_info& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sql.player_single_info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool player_single_info::IsInitialized() const {
  return true;
}

void player_single_info::InternalSwap(player_single_info* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uuid_, &other->_impl_.uuid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.names_, &other->_impl_.names_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(player_single_info, _impl_.avatar_)
      + sizeof(player_single_info::_impl_.avatar_)
      - PROTOBUF_FIELD_OFFSET(player_single_info, _impl_.guid_)>(
          reinterpret_cast<char*>(&_impl_.guid_),
          reinterpret_cast<char*>(&other->_impl_.guid_));
}

::google::protobuf::Metadata player_single_info::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class player_info::_Internal {
 public:
  using HasBits = decltype(std::declval<player_info>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(player_info, _impl_._has_bits_);
};

player_info::player_info(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sql.player_info)
}
inline PROTOBUF_NDEBUG_INLINE player_info::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::sql::player_info& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

player_info::player_info(
    ::google::protobuf::Arena* arena,
    const player_info& from)
    : ::google::protobuf::Message(arena) {
  player_info* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.single_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::sql::player_single_info>(
                              arena, *from._impl_.single_)
                        : nullptr;
  _impl_.array_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::sql::player_info_array>(
                              arena, *from._impl_.array_)
                        : nullptr;
  _impl_.kv_int_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::sql::player_info_kv_int>(
                              arena, *from._impl_.kv_int_)
                        : nullptr;
  _impl_.kv_str_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::sql::player_info_kv_str>(
                              arena, *from._impl_.kv_str_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:sql.player_info)
}
inline PROTOBUF_NDEBUG_INLINE player_info::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void player_info::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, single_),
           0,
           offsetof(Impl_, kv_str_) -
               offsetof(Impl_, single_) +
               sizeof(Impl_::kv_str_));
}
player_info::~player_info() {
  // @@protoc_insertion_point(destructor:sql.player_info)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void player_info::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.single_;
  delete _impl_.array_;
  delete _impl_.kv_int_;
  delete _impl_.kv_str_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
player_info::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(player_info, _impl_._cached_size_),
              false,
          },
          &player_info::MergeImpl,
          &player_info::kDescriptorMethods,
          &descriptor_table_sqlop_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 4, 0, 2> player_info::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(player_info, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_player_info_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sql::player_info>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .sql.player_info_kv_str kv_str = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 3, PROTOBUF_FIELD_OFFSET(player_info, _impl_.kv_str_)}},
    // .sql.player_single_info single = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(player_info, _impl_.single_)}},
    // .sql.player_info_array array = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(player_info, _impl_.array_)}},
    // .sql.player_info_kv_int kv_int = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(player_info, _impl_.kv_int_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .sql.player_single_info single = 1;
    {PROTOBUF_FIELD_OFFSET(player_info, _impl_.single_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .sql.player_info_array array = 2;
    {PROTOBUF_FIELD_OFFSET(player_info, _impl_.array_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .sql.player_info_kv_int kv_int = 3;
    {PROTOBUF_FIELD_OFFSET(player_info, _impl_.kv_int_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .sql.player_info_kv_str kv_str = 4;
    {PROTOBUF_FIELD_OFFSET(player_info, _impl_.kv_str_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::sql::player_single_info>()},
    {::_pbi::TcParser::GetTable<::sql::player_info_array>()},
    {::_pbi::TcParser::GetTable<::sql::player_info_kv_int>()},
    {::_pbi::TcParser::GetTable<::sql::player_info_kv_str>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void player_info::Clear() {
// @@protoc_insertion_point(message_clear_start:sql.player_info)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.single_ != nullptr);
      _impl_.single_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.array_ != nullptr);
      _impl_.array_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.kv_int_ != nullptr);
      _impl_.kv_int_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.kv_str_ != nullptr);
      _impl_.kv_str_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* player_info::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sql.player_info)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .sql.player_single_info single = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.single_, _impl_.single_->GetCachedSize(), target, stream);
  }

  // .sql.player_info_array array = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.array_, _impl_.array_->GetCachedSize(), target, stream);
  }

  // .sql.player_info_kv_int kv_int = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.kv_int_, _impl_.kv_int_->GetCachedSize(), target, stream);
  }

  // .sql.player_info_kv_str kv_str = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *_impl_.kv_str_, _impl_.kv_str_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sql.player_info)
  return target;
}

::size_t player_info::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sql.player_info)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // .sql.player_single_info single = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.single_);
    }

    // .sql.player_info_array array = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.array_);
    }

    // .sql.player_info_kv_int kv_int = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.kv_int_);
    }

    // .sql.player_info_kv_str kv_str = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.kv_str_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void player_info::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<player_info*>(&to_msg);
  auto& from = static_cast<const player_info&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:sql.player_info)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.single_ != nullptr);
      if (_this->_impl_.single_ == nullptr) {
        _this->_impl_.single_ =
            ::google::protobuf::Message::CopyConstruct<::sql::player_single_info>(arena, *from._impl_.single_);
      } else {
        _this->_impl_.single_->MergeFrom(*from._impl_.single_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.array_ != nullptr);
      if (_this->_impl_.array_ == nullptr) {
        _this->_impl_.array_ =
            ::google::protobuf::Message::CopyConstruct<::sql::player_info_array>(arena, *from._impl_.array_);
      } else {
        _this->_impl_.array_->MergeFrom(*from._impl_.array_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.kv_int_ != nullptr);
      if (_this->_impl_.kv_int_ == nullptr) {
        _this->_impl_.kv_int_ =
            ::google::protobuf::Message::CopyConstruct<::sql::player_info_kv_int>(arena, *from._impl_.kv_int_);
      } else {
        _this->_impl_.kv_int_->MergeFrom(*from._impl_.kv_int_);
      }
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.kv_str_ != nullptr);
      if (_this->_impl_.kv_str_ == nullptr) {
        _this->_impl_.kv_str_ =
            ::google::protobuf::Message::CopyConstruct<::sql::player_info_kv_str>(arena, *from._impl_.kv_str_);
      } else {
        _this->_impl_.kv_str_->MergeFrom(*from._impl_.kv_str_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void player_info::CopyFrom(const player_info& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sql.player_info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool player_info::IsInitialized() const {
  return true;
}

void player_info::InternalSwap(player_info* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(player_info, _impl_.kv_str_)
      + sizeof(player_info::_impl_.kv_str_)
      - PROTOBUF_FIELD_OFFSET(player_info, _impl_.single_)>(
          reinterpret_cast<char*>(&_impl_.single_),
          reinterpret_cast<char*>(&other->_impl_.single_));
}

::google::protobuf::Metadata player_info::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace sql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_sqlop_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
